AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 22

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false